name: Run Automated Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      groupToRun:
        type: choice
        description: Group to run
        options:
          - All Tests
          - smoke
          - regression

jobs:
  tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean Maven
        run: mvn clean

      - name: Install Maven Dependencies
        run: mvn install -DskipTests

      - name: Set Test Groups
        run: |
          if [[ -n "${{ github.event.inputs.groupToRun }}" ]]; then
            if [[ "${{ github.event.inputs.groupToRun }}" == "All Tests"]]; then
              echo "GROUPS=" >> $GITHUB_ENV
            else
              echo "GROUPS=${{ github.event.inputs.groupToRun }}" >> $GITHUB_ENV
            fi
          else 
            COMMIT_MSG=$(git log -1 --pretty=%B)
            if [[ "$COMMIT_MSG" =~ \[groups:([^\]]+)\] ]]; then
              echo "GROUPS=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            else
              echo "GROUPS=" >> $GITHUB_ENV
            fi
          fi

      - name: Run Tests
        run: |
          if [[ -n "$GROUPS" ]]; then
            mvn test -Dgroups="$GROUPS"
          else
            mvn test
          fi